use serde::{Deserialize, Serialize};
use std::borrow::Cow;

use crate::token;

// ─── Inbound Message ────────────────────────────────────────────────────────

/// Inbound message (from channel to gateway)
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct InboundMessage {
    pub channel: String,
    pub chat_id: String,
    pub sender_id: String,
    pub message_id: String,
    pub content: MessageContent,
    pub timestamp: i64,
    /// Unique trace ID for end-to-end request tracing. Generated by gateway if empty.
    #[serde(default)]
    pub trace_id: String,
    /// Image attachments for multimodal messages.
    #[serde(default)]
    pub images: Vec<ImageData>,
}

impl InboundMessage {
    /// Creates a heartbeat virtual message with the given prompt text.
    pub fn heartbeat(prompt: &str) -> Self {
        Self {
            channel: "__heartbeat__".into(),
            chat_id: "__heartbeat__".into(),
            sender_id: "__system__".into(),
            message_id: String::new(),
            content: MessageContent::Text(prompt.to_string()),
            timestamp: chrono::Utc::now().timestamp(),
            trace_id: uuid::Uuid::new_v4().to_string(),
            images: vec![],
        }
    }
}

// ─── Message Content ─────────────────────────────────────────────────────────

/// Base64-encoded image data for multimodal messages.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ImageData {
    /// MIME type, e.g. "image/jpeg", "image/png", "image/webp", "image/gif".
    pub media_type: String,
    /// Base64-encoded image bytes.
    pub data: String,
}

/// Message content — receiving supports multiple types; sending only uses Text.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", content = "data")]
pub enum MessageContent {
    Text(String),
    Image {
        key: String,
        /// Populated when the raw image bytes are available (e.g. HTTP upload).
        #[serde(default, skip_serializing_if = "Option::is_none")]
        image_data: Option<ImageData>,
    },
    File {
        key: String,
        name: String,
        /// Populated when the raw file bytes are available (e.g. HTTP upload).
        #[serde(default, skip_serializing_if = "Option::is_none")]
        file_bytes: Option<Vec<u8>>,
    },
    RichText(serde_json::Value),
}

impl MessageContent {
    /// Returns a plain-text representation of the content.
    pub fn to_text(&self) -> Cow<'_, str> {
        match self {
            MessageContent::Text(s) => Cow::Borrowed(s),
            MessageContent::Image { key, .. } => Cow::Owned(format!("[图片: {}]", key)),
            MessageContent::File { key: _, name, .. } => Cow::Owned(format!("[文件: {}]", name)),
            MessageContent::RichText(_) => Cow::Borrowed("[富文本消息]"),
        }
    }
}

// ─── Outbound Message ────────────────────────────────────────────────────────

/// Outbound message (from gateway to channel)
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OutboundMessage {
    pub channel: String,
    pub chat_id: String,
    pub reply_to: Option<String>,
    pub content: String,
}

impl OutboundMessage {
    /// Creates a reply targeting the same chat/channel as the inbound message.
    pub fn reply(msg: &InboundMessage, content: impl Into<String>) -> Self {
        Self {
            channel: msg.channel.clone(),
            chat_id: msg.chat_id.clone(),
            reply_to: (!msg.message_id.is_empty()).then(|| msg.message_id.clone()),
            content: content.into(),
        }
    }

    /// Creates an error reply targeting the same chat/channel as the inbound message.
    pub fn error(msg: &InboundMessage, error: &str) -> Self {
        Self::reply(msg, error)
    }
}

// ─── Role ────────────────────────────────────────────────────────────────────

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Role {
    System,
    User,
    Assistant,
    Tool,
}

// ─── Tool Types ──────────────────────────────────────────────────────────────

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ToolCall {
    pub id: String,
    pub name: String,
    pub arguments: serde_json::Value,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ToolResult {
    pub call_id: String,
    pub output: String,
    pub is_error: bool,
    #[serde(default)]
    pub duration_ms: u64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolDefinition {
    pub name: String,
    pub description: String,
    pub parameters: serde_json::Value,
}

// ─── Chat Message ────────────────────────────────────────────────────────────

/// LLM conversation message
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatMessage {
    pub role: Role,
    pub content: String,
    pub tool_calls: Option<Vec<ToolCall>>,
    pub tool_call_id: Option<String>,
    /// Optional image attachments (only used for User messages with vision).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub images: Option<Vec<ImageData>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub(crate) estimated_tokens: Option<usize>,
}

impl ChatMessage {
    fn new(role: Role, content: String) -> Self {
        Self {
            role,
            content,
            tool_calls: None,
            tool_call_id: None,
            images: None,
            estimated_tokens: None,
        }
    }

    /// Creates a System role message.
    pub fn system(content: &str) -> Self {
        Self::new(Role::System, content.to_string())
    }

    /// Creates a User role message.
    #[allow(dead_code)]
    pub fn user(content: &str) -> Self {
        Self::new(Role::User, content.to_string())
    }

    /// Creates a User role message with image attachments.
    /// Accepts a slice to avoid forcing callers to clone; only clones internally
    /// when images are present.
    pub fn user_with_images(content: &str, images: &[ImageData]) -> Self {
        let mut message = Self::new(Role::User, content.to_string());
        message.images = if images.is_empty() {
            None
        } else {
            Some(images.to_vec())
        };
        message
    }

    /// Creates an Assistant role message with no tool calls.
    pub fn assistant(content: &str) -> Self {
        Self::new(Role::Assistant, content.to_string())
    }

    /// Creates an Assistant role message that includes tool calls.
    pub fn assistant_with_tools(text: Option<&str>, calls: &[ToolCall]) -> Self {
        let mut message = Self::new(Role::Assistant, text.unwrap_or("").to_string());
        message.tool_calls = Some(calls.to_vec());
        message
    }

    /// Creates a Tool role message from a ToolResult.
    pub fn tool_result(result: &ToolResult) -> Self {
        let mut message = Self::new(Role::Tool, result.output.clone());
        message.tool_call_id = Some(result.call_id.clone());
        message
    }

    pub fn estimated_tokens(&self) -> Option<usize> {
        self.estimated_tokens
    }

    pub fn estimate_tokens_cached(&mut self) -> usize {
        *self
            .estimated_tokens
            .get_or_insert_with(|| token::estimate_message_tokens("msg", &self.content))
    }
}

// ─── LLM Response ────────────────────────────────────────────────────────────

/// An LLM response may contain both a text reply and tool calls simultaneously.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LlmResponse {
    pub text: Option<String>,
    pub tool_calls: Vec<ToolCall>,
}

/// A streaming event from LLM chat completion.
#[derive(Debug, Clone)]
pub enum StreamEvent {
    /// An incremental text delta.
    Delta(String),
    /// Stream complete; carries the full assembled response.
    Done(LlmResponse),
}
